#!/usr/bin/env bash
set -e

# HAITCH step control for full preprocessing + reconstruction, without topup.
# Only steps marked TODO will run.
declare -A FEDI_DMRI_PIPELINE_STEPS=(
  [STEP1_DWI_DENOISE_USING_GSVS]="TODO"
  [STEP2_MRDEGIBBS_RINGING_ARTI]="TODO"
  [STEP3_RICIAN_BIAS_CORRECTION]="TODO"
  [STEP4_FETAL_BRAIN_EXTRACTION]="TODO"
  [STEP5_SPLIT_CROP_SKDATA_MASK]="TODO"
  [STEP6_SLICECORRECTDISTORTION]="DONE"
  [STEP7_B1FIELDBIAS_CORRECTION]="TODO"
  [STEP8_3DSHORE_RECONSTRUCTION]="TODO"
  [STEP9_REGISTRATION_T2W_ATLAS]="DONE"
  [STEP10_TSOR_RESP_FOD_TRACTOG]="DONE"
)


export T2W_DATA="${T2W_DATA:-protocols/t2w}"
export T2W_RECON_METHOD="${T2W_RECON_METHOD:-SVRTK}"
export REGSTRAT="${REGSTRAT:-ants}"
export SEGMENTATION_METHOD="${SEGMENTATION_METHOD:-RAZIEH}"
export SING="${SING:-0}"
